
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jpant
 */
public class CadastroTanque extends javax.swing.JFrame {

    /**
     * Creates new form Tanque
     */
    private String id;
    private double volume, capacidade;
    
    public CadastroTanque(String id, double capacidade, double volume) {
        this.id = id;
        this.volume = volume;
        this.capacidade = capacidade;
        
        initComponents();
        setLocationRelativeTo(null);
        
        jLabel_id.setText(this.id);
        
        jProgressBar1.setOrientation(JProgressBar.VERTICAL); //JProgressBar.VERTICAL == 1
        
        jTextField_idTanque.setText(this.id);
        jTextField_capacidade.setText("" + this.capacidade);
        jTextField_volume.setText("" + this.volume);
        
        atualizaVolumeTanque();
        
        /** Configura tooltips para serem visualizados
         * embaixo dos elementos quando passa o mouse sobre
         * eles
        */
        jLabel_tuboEnsaio.setToolTipText("Tubo de ensaio");
        jLabel_insumo.setToolTipText("Insumo");
        jButton2.setToolTipText("Transferir conteúdo para outro tanque");
    }
    
    private void bugFixJProgressBar1(){
        jProgressBar1.setVisible(false);
        jProgressBar1.setVisible(true);
    }
    
    private void atualizaVolumeTanque(){
        jProgressBar1.setValue((int) (this.volume / this.capacidade * 100));
        jProgressBar1.updateUI();
        //bugFixJProgressBar1();
    }

    public void setVolume(double volume) throws Exception{
        if(volume <= capacidade)
            this.volume = volume;
        else
            throw new Exception("Volume excedeu a capacidade!");
    }

    public void setCapacidade(double capacidade) {
        this.capacidade = capacidade;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_tanque = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jTextField_idTanque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_capacidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_volume = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel_tuboEnsaio = new javax.swing.JLabel();
        jLabel_insumo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Cadastro de tanque");
        setSize(new java.awt.Dimension(600, 500));

        jTextField1.setText("29/02/2020 15:01:09");

        jLabel1.setText("Data-hora:");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_id.setText("A1");
        jPanel1.add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 40));

        jLabel_tanque.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_tanque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tanquePeq1.png"))); // NOI18N
        jPanel1.add(jLabel_tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));
        jProgressBar1.setForeground(new java.awt.Color(102, 0, 102));
        jProgressBar1.setValue(70);
        jProgressBar1.setString("80%");
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 83, 26, 134));

        jLabel2.setText("ID:");

        jTextField_idTanque.setText("A1");

        jLabel3.setText("Capacidade:");

        jTextField_capacidade.setText("100");
        jTextField_capacidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_capacidadeFocusLost(evt);
            }
        });

        jLabel4.setText("Volume:");

        jTextField_volume.setText("10");
        jTextField_volume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_volumeFocusLost(evt);
            }
        });

        jLabel5.setText("Variedade:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SAUVIGNON", "CHARDONNAY", "RIESLING", "PINOT NOIR", "MERLOT", "MALBEC", "CABERNET SAUVIGNON" }));

        jLabel6.setText("Temperatura (ºC):");

        jTextField2.setText("20");

        jTextField3.setText("20");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Densidade (g/cm³):");

        jLabel8.setText("Etapa:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fermetação do mosto" }));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel_tuboEnsaio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tuboEnsaio-48px.png"))); // NOI18N
        jLabel_tuboEnsaio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_tuboEnsaioMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_tuboEnsaio);
        jLabel_tuboEnsaio.getAccessibleContext().setAccessibleDescription("");

        jLabel_insumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Sugar-48x48.png"))); // NOI18N
        jLabel_insumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_insumoMouseClicked(evt);
            }
        });
        jPanel3.add(jLabel_insumo);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/insumos.png"))); // NOI18N
        jPanel3.add(jLabel9);

        jButton1.setText("Fechar tanque");

        jButton2.setText("Transfegar conteúdo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_idTanque)
                            .addComponent(jTextField_capacidade)
                            .addComponent(jTextField_volume)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_idTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_capacidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_capacidadeFocusLost
        // TODO add your handling code here:
        setCapacidade(Double.parseDouble(jTextField_capacidade.getText()));
        atualizaVolumeTanque();
    }//GEN-LAST:event_jTextField_capacidadeFocusLost

    private void jTextField_volumeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_volumeFocusLost
        try{
            setVolume(Double.parseDouble(jTextField_volume.getText()));
            atualizaVolumeTanque();
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Entrada inválida!", 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE
            );
            jTextField_volume.setText("" + volume);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(
                    rootPane, 
                    ex.getMessage(), "Erro", 
                    JOptionPane.ERROR_MESSAGE
            );
            jTextField_volume.setText("" + volume);
        }
    }//GEN-LAST:event_jTextField_volumeFocusLost

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
    
    TuboEnsaio tuboEnsaio;
    private void jLabel_tuboEnsaioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_tuboEnsaioMouseClicked
        // TODO add your handling code here:
        tuboEnsaio = new TuboEnsaio();
        tuboEnsaio.setVisible(true);
    }//GEN-LAST:event_jLabel_tuboEnsaioMouseClicked

    Insumo insumo;
    private void jLabel_insumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_insumoMouseClicked
        // TODO add your handling code here:
        insumo = new Insumo();
        insumo.setVisible(true);
    }//GEN-LAST:event_jLabel_insumoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_insumo;
    private javax.swing.JLabel jLabel_tanque;
    private javax.swing.JLabel jLabel_tuboEnsaio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_capacidade;
    private javax.swing.JTextField jTextField_idTanque;
    private javax.swing.JTextField jTextField_volume;
    // End of variables declaration//GEN-END:variables
}
