
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jpant
 */
public class Cantina extends javax.swing.JFrame {

    /**
     * Creates new form Cantina
     */
    public Cantina() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cantina");
        getContentPane().setLayout(new java.awt.FlowLayout());
        getAccessibleContext().setAccessibleName("Cantina");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Cantina cantina = new Cantina();
        int T = 11;
        Tanque tanques[] = new Tanque[T];
        for(int i=0; i<T; i++) {
            tanques[i] = new Tanque("A"+i, 100, 10*i);
            tanques[i].setVisible(true);
            cantina.add(tanques[i]);
        }
//        tanques[0] = new Tanque("A"+0, 100, 70);
//        tanques[0].setVisible(true);
//        cantina.add(tanques[0]);
//        
//        tanques[1] = new Tanque("A"+1, 100, 10);
//        tanques[1].setVisible(true);
//        cantina.add(tanques[1]);
        
        cantina.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
