
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jpant
 */
public class Tanque extends javax.swing.JPanel {

    /**
     * Creates new form Tanque
     */
    private String id;
    private double volume, capacidade;
    
    public Tanque(String id, double capacidade, double volume) {
        this.id = id;
        this.volume = volume;
        this.capacidade = capacidade;
        
        initComponents();
        jLabel_id.setText(this.id);
        
        jProgressBar1.setOrientation(JProgressBar.VERTICAL); //JProgressBar.VERTICAL == 1
        jProgressBar1.setValue((int) (this.volume / this.capacidade * 100));
    }
    
    private void bugFixJProgressBar1(){
        jProgressBar1.setVisible(false);
        jProgressBar1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_id = new javax.swing.JLabel();
        jLabel_tanque = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_id.setForeground(java.awt.SystemColor.activeCaptionBorder);
        jLabel_id.setText("A1");
        add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 40));

        jLabel_tanque.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel_tanque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tanquePeq1.png"))); // NOI18N
        jLabel_tanque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_tanqueMouseClicked(evt);
            }
        });
        add(jLabel_tanque, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));
        jProgressBar1.setForeground(new java.awt.Color(102, 0, 102));
        jProgressBar1.setValue(70);
        add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 72, 26, 134));
    }// </editor-fold>//GEN-END:initComponents
    CadastroTanque cadastroTanque;
    private void jLabel_tanqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_tanqueMouseClicked
        // TODO add your handling code here:
        cadastroTanque = new CadastroTanque(id, capacidade, volume);
        cadastroTanque.setVisible(true);
    }//GEN-LAST:event_jLabel_tanqueMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_tanque;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
